language: csharp
mono: none
dotnet: 3.1.410
solution: RiceItems.sln
script:
  - dotnet restore
  - dotnet test
  - sudo apt install nuget
  - mozroots --import --sync
  - nuget install OpenCover -OutputDirectory opencover
  - nuget install coveralls.io
  - opencover\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[RiceItemsTests*]*" -output:".\RiceItems_coverage.xml" -oldstyle
  - coveralls\1.4.2\tools\coveralls.net.exe --opencover RiceItems_coverage.xml -r %COVERALLS_REPO_TOKEN%